### PR TITLE
KTH-50 - Create Docker Compose for local development

### LINKED ISSUE #68: Create a docker-compose for db and server
Within docker/dev/ make it possible to run twiga without setting up your own postgres on your computer. Instead do it in the container.

### PR DESCRIPTION
**Pull request by alvaro-mazcu**
This PR intoduces:
* A Makefile for simplifying local data generation and Docker containers management.
* A new way of running Twiga locally with Docker Compose.
* A specific Docker image for the DB, with the installation of pgvector.
* 5 new env-vars for DB (needed for the DB, although they are not critical).
* Code simplification

This PR aims to simplify the local development process by encapsulating all affected services in a Docker Compose. Now, DB no longer depends on a PostgreSQL running in ones computer, creating an specific image for it and for running it in the compose. This change should:
* Fix pgvector error that some colleagues were having (mostly windows-based computers).
* Close #68 

I have updated the GETTING_STARTED.md with the new way of running Twiga. Much simpler than before.

#### How to test?

- [ ] Recreate your local environment completely. For doing this you might need to execute in a SQL terminal the following commands:

```sql
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
```
- [ ] Follow the steps of GETTING_STARTED.md. Everything should run smoothly 👍

cc @jurmy24 @fredygerman @louhelhir

### CODE REVIEW

**Comment by jurmy24** [comment]
Hi @alvaro-mazcu. Great work! 

I have a few comments/questions:

1. We have a lot of environment variables already, and all info in the first 5 env variables below are contained within the 6th and can be extracted using the `urlparse()` function. 

```shell
DATABASE_USER=$YOUR_USER
DATABASE_PASSWORD=$YOUR_PASSWORD
DATABASE_SERVER_NAME=db
DATABASE_PORT=5432
DATABASE_NAME=$YOUR_DB_NAME
DATABASE_URL=postgresql+asyncpg://$YOUR_USER:$YOUR_PASSWORD@db:5432/$YOUR_DB_NAME
```
I see you use these directly in the docker-compose. Is there a way to extract them from the DATABASE_URL instead to avoid the duplication?

2. Is it more reasonable to store the docker-compose file within the docker folder under `docker/dev`? Let me know what you think.

3. Do you think it makes more sense that this is the default way to run twiga as a new contributor and have that as the main approach in the documentation? (and then just say that if you want to run it without docker contact us or something)

4. Try to use the commit conventions where you write keyword(scope): short description \n LINEAR-TAG

5. run `pre-commit run --all-files` to make sure your code is properly formatted and that it passes all the tests. If you haven't used pre-commit before you can check the CONTRIBUTING.md file. 

Also, thanks for moving the `get_database_url()` file into utils. It makes more sense to have it there.

**Review by jurmy24 — CHANGES_REQUESTED** [review]
Hi @alvaro-mazcu. Great work! 

I have a few comments/questions:

1. We have a lot of environment variables already, and all info in the first 5 env variables below are contained within the 6th and can be extracted using the `urlparse()` function. 

```shell
DATABASE_USER=$YOUR_USER
DATABASE_PASSWORD=$YOUR_PASSWORD
DATABASE_SERVER_NAME=db
DATABASE_PORT=5432
DATABASE_NAME=$YOUR_DB_NAME
DATABASE_URL=postgresql+asyncpg://$YOUR_USER:$YOUR_PASSWORD@db:5432/$YOUR_DB_NAME
```
I see you use these directly in the docker-compose. Is there a way to extract them from the DATABASE_URL instead to avoid the duplication?

2. Is it more reasonable to store the docker-compose file within the docker folder under `docker/dev`? Let me know what you think.

3. Do you think it makes more sense that this is the default way to run twiga as a new contributor and have that as the main approach in the documentation? (and then just say that if you want to run it without docker contact us or something)

4. Try to use the commit conventions where you write keyword(scope): short description \n LINEAR-TAG

5. run `pre-commit run --all-files` to make sure your code is properly formatted and that it passes all the tests. If you haven't used pre-commit before you can check the CONTRIBUTING.md file. 

Also, thanks for moving the `get_database_url()` file into utils. It makes more sense to have it there.

**Comment by alvaro-mazcu** [comment]
> We have a lot of environment variables already, and all info in the first 5 env variables below are contained within the 6th and can be extracted using the urlparse() function.
DATABASE_USER=$YOUR_USER
DATABASE_PASSWORD=$YOUR_PASSWORD
DATABASE_SERVER_NAME=db
DATABASE_PORT=5432
DATABASE_NAME=$YOUR_DB_NAME
DATABASE_URL=postgresql+asyncpg://$YOUR_USER:$YOUR_PASSWORD@db:5432/$YOUR_DB_NAME
I see you use these directly in the docker-compose. Is there a way to extract them from the DATABASE_URL instead to avoid the duplication?

Yep, i think there's a way. They are not extremely important (I was testing with them and I include them into the PR, but I can delete them)

**Comment by alvaro-mazcu** [comment]
> Is it more reasonable to store the docker-compose file within the docker folder under docker/dev? Let me know what you think.

It's ok, i placed it in the root for convenience. The difference will be at the time of running the compose: `docker-compose -f /path/to/your/docker-compose.yml command`vs `docker-compose up`. I don't really care much about it, so it's up to you 😇

**Comment by jurmy24** [comment]
> > Is it more reasonable to store the docker-compose file within the docker folder under docker/dev? Let me know what you think.
> 
> It's ok, i placed it in the root for convenience. The difference will be at the time of running the compose: `docker-compose -f /path/to/your/docker-compose.yml command`vs `docker-compose up`. I don't really care much about it, so it's up to you 😇

I think it's cleaner to put it in the docker folder in whatever specific place makes most sense. Then you can just modify the docker compose command in the docs.

**Comment by jurmy24** [comment]
> > Do you think it makes more sense that this is the default way to run twiga as a new contributor and have that as the main approach in the documentation? (and then just say that if you want to run it without docker contact us or something)
> 
> I think so, yeah. It's just 2-3 commands, much less than before, and replicable in all types of hardware :)

Great, then we do it that way.

**Review by jurmy24 — DISMISSED** [review]
If you remove the unnecessary environment variables, move the docker-compose into the docker folder, ensure it runs as expected, and do a new PR I'll test it myself and approve it. 🥇 

I'll probably modify the init_twigadb file later so that we don't need to recreate the embeddings each time.

**Review by jurmy24 — APPROVED** [review]
Looks good to me! 👍

**Pull request merged**
